INSERT INTO varselkode(kode, avviklet) VALUES
                                           ('RV_SY_1', true),
                                           ('RV_SY_2', true),
                                           ('RV_SY_3', true),
                                           ('RV_SØ_1', false),
                                           ('RV_SØ_2', false),
                                           ('RV_SØ_3', false),
                                           ('RV_SØ_4', false),
                                           ('RV_SØ_5', false),
                                           ('RV_SØ_6', true),
                                           ('RV_SØ_7', false),
                                           ('RV_SØ_8', false),
                                           ('RV_SØ_9', true),
                                           ('RV_SØ_10', false),
                                           ('RV_SØ_11', false),
                                           ('RV_SØ_12', false),
                                           ('RV_SØ_13', false),
                                           ('RV_SØ_14', true),
                                           ('RV_SØ_15', false),
                                           ('RV_SØ_16', false),
                                           ('RV_SØ_17', false),
                                           ('RV_SØ_18', true),
                                           ('RV_SØ_19', false),
                                           ('RV_SØ_20', false),
                                           ('RV_SØ_21', true),
                                           ('RV_SØ_22', false),
                                           ('RV_SØ_23', true),
                                           ('RV_SØ_24', true),
                                           ('RV_SØ_25', true),
                                           ('RV_SØ_26', true),
                                           ('RV_OO_1', false),
                                           ('RV_OO_2', false),
                                           ('RV_IM_1', false),
                                           ('RV_IM_2', false),
                                           ('RV_IM_3', false),
                                           ('RV_IM_4', false),
                                           ('RV_IM_5', false),
                                           ('RV_IM_6', false),
                                           ('RV_IM_7', false),
                                           ('RV_IM_8', false),
                                           ('RV_IM_9', true),
                                           ('RV_IM_10', true),
                                           ('RV_IM_11', true),
                                           ('RV_IM_12', true),
                                           ('RV_IM_13', true),
                                           ('RV_IM_14', true),
                                           ('RV_IM_15', true),
                                           ('RV_IM_16', true),
                                           ('RV_IM_17', true),
                                           ('RV_IM_18', true),
                                           ('RV_IM_19', true),
                                           ('RV_ST_1', false),
                                           ('RV_RE_1', false),
                                           ('RV_RE_2', false),
                                           ('RV_IT_1', false),
                                           ('RV_IT_2', true),
                                           ('RV_IT_3', false),
                                           ('RV_IT_4', false),
                                           ('RV_IT_5', true),
                                           ('RV_IT_6', false),
                                           ('RV_IT_7', false),
                                           ('RV_IT_8', false),
                                           ('RV_IT_9', false),
                                           ('RV_IT_10', false),
                                           ('RV_IT_11', false),
                                           ('RV_IT_12', false),
                                           ('RV_IT_13', false),
                                           ('RV_IT_14', false),
                                           ('RV_IT_15', false),
                                           ('RV_IT_16', false),
                                           ('RV_IT_17', false),
                                           ('RV_IT_18', true),
                                           ('RV_IT_19', true),
                                           ('RV_IT_20', true),
                                           ('RV_IT_21', true),
                                           ('RV_IT_22', true),
                                           ('RV_IT_23', true),
                                           ('RV_IT_24', true),
                                           ('RV_IT_25', true),
                                           ('RV_IT_26', true),
                                           ('RV_IT_27', true),
                                           ('RV_IT_28', true),
                                           ('RV_IT_29', true),
                                           ('RV_IT_30', true),
                                           ('RV_IT_31', true),
                                           ('RV_IT_32', true),
                                           ('RV_IT_33', false),
                                           ('RV_VV_1', false),
                                           ('RV_VV_2', false),
                                           ('RV_VV_3', true),
                                           ('RV_VV_4', false),
                                           ('RV_VV_5', false),
                                           ('RV_VV_8', false),
                                           ('RV_VV_9', false),
                                           ('RV_VV_10', false),
                                           ('RV_VV_11', false),
                                           ('RV_VV_12', false),
                                           ('RV_VV_13', true),
                                           ('RV_VV_14', true),
                                           ('RV_VV_15', true),
                                           ('RV_VV_16', true),
                                           ('RV_OV_1', false),
                                           ('RV_OV_2', true),
                                           ('RV_MV_1', false),
                                           ('RV_MV_2', false),
                                           ('RV_IV_1', false),
                                           ('RV_IV_2', false),
                                           ('RV_IV_3', false),
                                           ('RV_IV_4', true),
                                           ('RV_IV_5', true),
                                           ('RV_IV_6', true),
                                           ('RV_SV_1', false),
                                           ('RV_SV_2', false),
                                           ('RV_SV_3', false),
                                           ('RV_SV_4', true),
                                           ('RV_AY_3', false),
                                           ('RV_AY_4', false),
                                           ('RV_AY_5', false),
                                           ('RV_AY_6', false),
                                           ('RV_AY_7', false),
                                           ('RV_AY_8', false),
                                           ('RV_AY_9', false),
                                           ('RV_AY_10', false),
                                           ('RV_SI_1', false),
                                           ('RV_SI_2', false),
                                           ('RV_SI_3', false),
                                           ('RV_SI_4', true),
                                           ('RV_SI_5', true),
                                           ('RV_SI_6', true),
                                           ('RV_SI_7', true),
                                           ('RV_UT_1', false),
                                           ('RV_UT_2', false),
                                           ('RV_UT_3', false),
                                           ('RV_UT_4', false),
                                           ('RV_UT_5', false),
                                           ('RV_UT_6', false),
                                           ('RV_UT_7', false),
                                           ('RV_UT_8', false),
                                           ('RV_UT_9', false),
                                           ('RV_UT_10', false),
                                           ('RV_UT_11', false),
                                           ('RV_UT_12', false),
                                           ('RV_UT_13', false),
                                           ('RV_UT_14', false),
                                           ('RV_UT_15', false),
                                           ('RV_UT_16', false),
                                           ('RV_UT_17', false),
                                           ('RV_UT_18', false),
                                           ('RV_UT_19', false),
                                           ('RV_UT_20', true),
                                           ('RV_UT_21', true),
                                           ('RV_OS_1', false),
                                           ('RV_OS_2', false),
                                           ('RV_OS_3', false),
                                           ('RV_RV_1', false),
                                           ('RV_RV_2', false),
                                           ('RV_RV_3', true),
                                           ('RV_RV_4', true),
                                           ('RV_RV_5', true),
                                           ('RV_VT_1', false),
                                           ('RV_VT_2', false),
                                           ('RV_VT_3', false),
                                           ('RV_VT_4', false),
                                           ('RV_VT_5', false),
                                           ('RV_VT_6', false),
                                           ('RV_VT_7', false),
                                           ('RV_AG_1', false),
                                           ('SB_BO_1', false),
                                           ('SB_BO_2', false),
                                           ('SB_BO_3', false),
                                           ('SB_BO_4', false),
                                           ('SB_BO_5', true),
                                           ('SB_EX_1', false),
                                           ('SB_EX_2', true),
                                           ('SB_EX_3', false),
                                           ('SB_IK_1', false),
                                           ('SB_RV_1', false),
                                           ('SB_RV_2', false),
                                           ('SB_RV_3', false)
ON CONFLICT(kode) DO NOTHING;

INSERT INTO varsel_definisjon(varselkode_ref, tittel, forklaring, handling) VALUES
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SY_1'), 'Korrigert sykmelding er lagt til grunn - kontroller dagene i sykmeldingsperioden', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SY_2'), 'Mottatt en sykmelding som er skrevet tidligere enn den som er lagt til grunn, vurder sykmeldingene og gjør eventuelle justeringer', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SY_3'), 'Mottatt flere sykmeldinger for perioden - den første sykmeldingen som ble mottatt er lagt til grunn. Utbetal kun hvis det blir korrekt', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_1'), 'Søknaden inneholder permittering. Vurder om permittering har konsekvens for rett til sykepenger', 'Bruker har oppgitt permittering på søknad om sykepenger', 'Kontrollér at permitteringen ikke påvirker sykepengerettighetene'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_2'), 'Minst én dag er avslått på grunn av foreldelse. Vurder å sende vedtaksbrev fra Infotrygd', 'Søknaden har kommet inn mer enn 3 måneder før dagen/dagene.', 'Hvis det ikke finnes noe unntak fra foreldelsesfristen skal du godkjenne i Speil og sende vedtaksbrev fra Infotrygd. Hvis forslaget er feil må du avvise saken i Speil og behandle i Infotrygd. Dersom dagen/dagene som er avslått er innenfor arbeidsgiverperioden trenger du ikke å sende avslag fra Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_3'), 'Sykmeldingen er tilbakedatert, vurder fra og med dato for utbetaling.', 'Sykmeldingen er tilbakedatert.', 'Hvis tilbakedateringen er godkjent, skal du finne notat i Gosys eller stå i fritekstfelt på SP-UB. Da kan du godkjenne saken i Speil. Hvis tilbakedateringen er under vurdering, skal det være en åpen Gosys-oppgave. I slike tilfeller skal du legge saken på vent til vurderingen er ferdig. Hvis tilbakedateringen er avslått, skal du avvise saken i Speil og sende vedtak. Registerer avslaget i SP-SA. Husk også å lukke oppgaven på søknaden/inntektsmeldingen i Gosys.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_4'), 'Utdanning oppgitt i perioden i søknaden.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_5'), 'Søknaden inneholder Permisjonsdager utenfor sykdomsvindu', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_6'), 'Søknaden inneholder egenmeldingsdager etter sykmeldingsperioden', 'Det foreligger egenmeldingsdager etter sykmeldingsperioden', 'Egenmeldinger kan ikke benyttes rett etter en sykmelding, sjekk arbeidsgiverperioden og utbetalingsoversikten.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_7'), 'Søknaden inneholder Arbeidsdager utenfor sykdomsvindu', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_8'), 'Utenlandsopphold oppgitt i perioden i søknaden.', 'Det er oppgitt utenlandsopphold utenfor EØS i søknaden', 'Undersøk om det er vedtak om beholde sykepenger under utenlandsopphold. Hvis det er søkt uten at det er behandlet - legg saken på vent til det foreligger vedtak i saken. Korriger dager dersom det er gitt avslag - og godkjenn saken i ny løsning. Hvis brukeren har fått vedtak fra NAV-kontoret, trenger du ikke å sende nytt vedtak.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_9'), 'Det er oppgitt annen inntektskilde i søknaden. Vurder inntekt.', 'Den sykmeldte har oppgitt «Annet» som annen inntektskilde i søknaden.', 'Sjekk hva den andre inntektskilden består av og vurder om saken kan behandles i Speil. Hvis saken ikke kan behandles i Speil, må du behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_10'), 'Den sykmeldte har fått et nytt inntektsforhold.', 'Den sykmeldte har oppgitt i søknaden at han/hun har fått et nytt inntektsforhold i sykmeldingsperioden.', 'Du må sjekke om sykepengene skal graderes ut ifra inntekt i det nye inntektsforholdet. Du må finne informasjon om inntekten og når den er opptjent. Ta stilling til om det bør sendes en oppgave til NAV-kontoret for vurdering av vilkårene i § 8-4.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_11'), 'Mottatt søknad out of order', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_12'), 'Mottatt overlappende søknad', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_13'), 'Overlappende søknad starter før, eller slutter etter, opprinnelig periode', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_14'), 'Mottatt flere søknader for annen periode enn siste skjæringstidspunkt', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_15'), 'Mottatt flere søknader for perioden - siste søknad inneholder arbeidsdag', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_16'), 'Mottatt flere søknader for perioden - det støttes ikke før replay av hendelser er på plass', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_17'), 'Søker er ikke gammel nok på søknadstidspunktet til å søke sykepenger uten fullmakt fra verge', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_18'), 'Søknaden inneholder andre inntektskilder enn ANDRE_ARBEIDSFORHOLD', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_19'), 'Søknad forlenger en forkastet periode', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_20'), 'Søknad overlapper med, eller er før, en forkastet vedtaksperiode', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_21'), 'Bruker har oppgitt at de har jobbet mindre enn sykmelding tilsier', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_22'), 'Søknaden inneholder en Papirsykmeldingsperiode', 'Sjekk om papirsykmeldingen er med i arbeidsgiverperioden hvis det er en førstegangssak. Sjekk om papirsykmeldingen medfører endring i grad hvis det er en forlengelse.', 'Utbetal kun hvis arbeidsgiverperioden er korrekt. Korriger eventuelt grad.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_23'), 'Korrigert søknad er mottatt med nye opplysninger - kontroller dagene i sykmeldingsperioden', 'Det har kommet en korrigert søknad som er lagt til grunn', 'Kontroller at dagene i sykmeldingsperioden blir riktig'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_24'), 'Mottatt flere søknade for perioden - den første søknaden som ble mottatt er lagt til grunn. Utbetal kun hvis det blir korrekt', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_25'), 'Permisjon oppgitt i perioden i søknaden. Vurder rett til sykepenger og korriger sykmeldingsperioden', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SØ_26'), 'Søknaden inneholder Feriedager utenfor perioden søknaden gjelder for', 'I søknadsdialogen så blir den sykmeldte spurt om det er ferie i mellomliggende periode. Dette for å finne ut om to perioder hører sammen og om man trenger inntektsmelding.', 'Undersøk om perioden blir riktig beregnet.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_OO_1'), 'Det er behandlet en søknad i Speil for en senere periode enn denne.', 'Søknadene har ikke kommet i vanlig rekkefølge. Dette kan skje dersom den sykmeldte avbryter en søknad/sykmelding, eller en lege skriver ut en tilbakedatert sykmelding. Perioder som allerede er avsluttet vil revurderes når denne perioden godkjennes.', 'Undersøk at behandlingen av perioden blir riktig.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_OO_2'), 'Saken må revurderes fordi det har blitt behandlet en tidligere periode som kan ha betydning.', 'Det har blitt behandlet en søknadsperiode som gjelder et tidligere tidsrom. Dette kan medføre at antall forbrukte dager er endret eller at opptjening av ny rett til sykepenger påvirkes.', 'Sjekk at telling av forbrukte dager og/eller opptjening av ny rett er riktig beregnet. Dersom revurderingen gjør at det er for mye utbetalt til den sykmeldte, se egne rutiner for håndtering av feilutbetalinger.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_1'), 'Vi har mottatt en inntektsmelding i en løpende sykmeldingsperiode med oppgitt første/bestemmende fraværsdag som er ulik tidligere fastsatt skjæringstidspunkt.', 'Det kan bety at den sykmeldte har gjenopptatt arbeidet og så blitt sykmeldt igjen. Det kan derfor være et nytt skjæringstidspunkt.', 'Undersøk om arbeidet er gjenopptatt slik at sykmeldingen avbrytes. Det må avklares om det blir et nytt skjæringstidspunkt. Hvis det blir nytt skjæringstidspunkt, må perioden med det nye skjæringstidspunktet avvises i vedtaksløsningen og saken må behandles i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_2'), 'Første fraværsdag i inntektsmeldingen er ulik skjæringstidspunktet. Kontrollér at inntektsmeldingen er knyttet til riktig periode.', 'Første fraværsdag i inntektsmeldingen er ulik første fraværsdag i sykdomsperioden:', 'Kontroller at skjæringstidspunktet er riktig.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_3'), 'Inntektsmeldingen og vedtaksløsningen er uenige om beregningen av arbeidsgiverperioden. Undersøk hva som er riktig arbeidsgiverperiode.', 'Arbeidsgiver og vedtaksløsningen har beregnet arbeidsgiverperioden ulikt.', 'Vurder hva som er riktig arbeidsgiverperiode. Hvis forslaget til vedtaksløsningen er feil, må saken behandles i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_4'), 'Mottatt flere inntektsmeldinger - den første inntektsmeldingen som ble mottatt er lagt til grunn. Utbetal kun hvis det blir korrekt.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_5'), 'Sykmeldte har oppgitt ferie første dag i arbeidsgiverperioden.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_6'), 'Inntektsmelding inneholder ikke beregnet inntekt', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_7'), 'Brukeren har opphold i naturalytelser', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_8'), 'Arbeidsgiver har redusert utbetaling av arbeidsgiverperioden', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_9'), 'ArbeidsforholdsID fra inntektsmeldingen er utfylt', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_10'), 'Første fraværsdag i inntektsmeldingen er forskjellig fra foregående tilstøtende periode', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_11'), 'Første fraværsdag i inntektsmeldingen er ulik første fraværsdag i sykdomsperioden', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_12'), 'Første fraværsdag i inntektsmeldingen er utenfor søknadsperioden. Kontroller at inntektsmeldingen er knyttet til riktig periode', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_13'), 'Første fraværsdag i inntektsmeldingen er utenfor sykmeldingsperioden', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_14'), 'Første fraværsdag oppgitt i inntektsmeldingen er ulik den systemet har beregnet. Utbetal kun hvis dagsatsen er korrekt', 'Det er forskjell mellom det arbeidsgiver har oppgitt som første fraværsdag og sykmeldingens fra og med-dato.', 'Sjekk om dagsatsen er riktig, og om saken faktisk er under 25 prosent avvik med sammenligningsgrunnlaget.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_15'), 'Første fraværsdag oppgitt i inntektsmeldingen er ulik den systemet har beregnet. Vurder hvilken inntektsmelding som skal legges til grunn, og utbetal kun hvis dagsatsen er korrekt i forhold til denne.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_16'), 'Inntektsmelding inneholder ikke arbeidsgiverperiode', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_17'), 'Inntektsmelding inneholder ikke arbeidsgiverperiode. Vurder om  arbeidsgiverperioden beregnes riktig', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_18'), 'Inntektsmeldingen mangler arbeidsgiverperiode. Vurder om vilkårene for sykepenger er oppfylt, og om det skal være arbeidsgiverperiode', 'Selvforklarende. Oppstår dersom inntektsmelding kommer inn for et arbeidsforhold bruker ikke er sykmeldt i.', 'Kontrollér at det kun er én arbeidsgiver. Skal kun komme ved flere arbeidsforhold i samme virksomhet.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IM_19'), 'Mottatt flere inntektsmeldinger - den andre inntektsmeldingen som ble mottatt er lagt til grunn. Utbetal kun hvis det blir korrekt.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_ST_1'), 'Sykdomstidslinjen inneholder ustøttet dag.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_RE_1'), 'Fant ikke refusjonsgrad for perioden. Undersøk oppgitt refusjon før du utbetaler.', 'Fant ikke informasjon om det er refusjon i perioden. Refusjonen er satt til 100 % siden det samsvarer med siste utbetalte periode i Infotrygd.', 'Undersøk hva som er oppgitt i siste inntektsmelding og eventuell informasjon i Infotrygd. Dersom refusjonen er satt feil må perioden behandles i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_RE_2'), 'Mangler refusjonsopplysninger', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_1'), 'Det er utbetalt en periode i Infotrygd etter perioden du skal behandle nå. Undersøk at antall forbrukte dager og grunnlag i Infotrygd er riktig', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_2'), 'Perioden er lagt inn i Infotrygd, men ikke utbetalt. Fjern fra Infotrygd hvis det utbetales via speil.', 'Det ligger registrert en søknad om sykepenger på SP UB.', 'Dette varselet betyr ikke at perioden må behandles i Infotrygd. Fjern perioden fra SP UB når du utbetaler via speil. Hvis inntekten er registert så kan den slettes på SP-VT. Hvis det er en forutgående periode i Infotrygd som enda ikke er behandlet, trenger du ikke å avvise perioden hvis det er flere sykepengedager igjen er enn det som ligger til behandling i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_3'), 'Utbetaling i Infotrygd overlapper med vedtaksperioden', 'Denne sakstypen tas normalt ikke inn i Speil. Det kan ha skjedd en endring fra saken ble behandlet første gang til den nå skal revurderes.', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_4'), 'Det er registrert utbetaling på nødnummer', 'Denne sakstypen tas normalt ikke inn i Speil. Det kan ha skjedd en endring fra saken ble behandlet første gang til den nå skal revurderes.', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_5'), 'Mangler inntekt for første utbetalingsdag i en av infotrygdperiodene', 'Denne sakstypen tas normalt ikke inn i Speil. Det kan ha skjedd en endring fra saken ble behandlet første gang til den nå skal revurderes.', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_6'), 'Det er en ugyldig utbetalingsperiode i Infotrygd (mangler fom- eller tomdato)', 'Det er lest inn en utbetalingsperiode fra Infotrygd som er mangelfull. Det er fire ulike årsaker til at dette kan skje: Utbetalingsperioden mangler f.o.m. eller t.o.m. dato. F.o.m. er nyere enn t.o.m. Utbetalingsgrad mangler. Utbetalingsgrad er mindre eller lik 0', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_7'), 'Det er en ugyldig utbetalingsperiode i Infotrygd (fom er nyere enn tom)', 'Det er lest inn en utbetalingsperiode fra Infotrygd som er mangelfull. Det er fire ulike årsaker til at dette kan skje: Utbetalingsperioden mangler f.o.m. eller t.o.m. dato. F.o.m. er nyere enn t.o.m. Utbetalingsgrad mangler. Utbetalingsgrad er mindre eller lik 0', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_8'), 'Det er en ugyldig utbetalingsperiode i Infotrygd (utbetalingsgrad mangler)', 'Det er lest inn en utbetalingsperiode fra Infotrygd som er mangelfull. Det er fire ulike årsaker til at dette kan skje: Utbetalingsperioden mangler f.o.m. eller t.o.m. dato. F.o.m. er nyere enn t.o.m. Utbetalingsgrad mangler. Utbetalingsgrad er mindre eller lik 0', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_9'), 'Det er en ugyldig utbetalingsperiode i Infotrygd (utbetalingsgrad er mindre eller lik 0)', 'Det er lest inn en utbetalingsperiode fra Infotrygd som er mangelfull. Det er fire ulike årsaker til at dette kan skje: Utbetalingsperioden mangler f.o.m. eller t.o.m. dato. F.o.m. er nyere enn t.o.m. Utbetalingsgrad mangler. Utbetalingsgrad er mindre eller lik 0', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_10'), 'Det er en ugyldig utbetalingsperiode i Infotrygd', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_11'), 'Det er registrert bruk av på nødnummer', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_12'), 'Organisasjonsnummer for inntektsopplysning fra Infotrygd mangler', 'Denne sakstypen tas normalt ikke inn i Speil. Det kan ha skjedd en endring fra saken ble behandlet første gang til den nå skal revurderes.', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_13'), 'Støtter ikke overgang fra infotrygd for flere arbeidsgivere', 'Denne sakstypen tas normalt ikke inn i Speil. Det kan ha skjedd en endring fra saken ble behandlet første gang til den nå skal revurderes.', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_14'), 'Forlenger en Infotrygdperiode på tvers av arbeidsgivere', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_15'), 'Personen er ikke registrert som normal arbeidstaker i Infotrygd', 'Denne sakstypen tas normalt ikke inn i Speil. Det kan ha skjedd en endring fra saken ble behandlet første gang til den nå skal revurderes.', 'Undersøk om saken kan revurderes i Speil og at utbetalingen blir riktig. Hvis saken ikke kan revurderes i Speil, må du annullere og behandle saken i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_16'), 'Støtter ikke saker med vilkårsgrunnlag i Infotrygd', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_17'), 'Forespurt overstyring av inntekt hvor skjæringstidspunktet ligger i infotrygd', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_18'), 'Avslutter perioden fordi tilstøtende, eller nyere periode, gikk til Infotrygd', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_19'), 'Dagsatsen har endret seg minst én gang i en historisk, sammenhengende periode i Infotrygd.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_20'), 'Det er en utbetalingsperiode som er lagt inn i Infotrygd uten at inntektsopplysninger er registrert.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_21'), 'Det er lagt inn flere inntekter i Infotrygd med samme fom-dato, den seneste er lagt til grunn. Kontroller sykepengegrunnlaget.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_22'), 'Det er lagt inn statslønn i Infotrygd, undersøk at utbetalingen blir riktig.', 'Det ligger statslønn på en SP VT-ident i Infotrygd', 'Kontrollér at bruker kun har ett arbeidsforhold/inntektskilde i det sykefraværet som skal dekkes i Speil'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_23'), 'Direkte overgang fra Infotrygd. Dagsatsen har endret seg minst én gang i Infotrygd. Kontroller at sykepengegrunnlaget er riktig.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_24'), 'Forkaster perioden fordi vi har oppdaget utbetalinger i Infotrygd', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_25'), 'Har utbetalt periode i Infotrygd nærmere enn 18 dager fra første dag', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_26'), 'Infotrygd inneholder utbetalinger med varierende dagsats for en sammenhengende periode', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_27'), 'Opplysninger fra Infotrygd har endret seg etter at vedtaket ble fattet. Undersøk om det er overlapp med periode fra Infotrygd.', 'Vi fikk informasjon fra Infotrygd som er annerledes enn da vedtaket ble fattet.', 'Hvis en periode overlapper med Infotrygd så må utbetalingen i Infotrygd returføres. Undersøk også om opplysningene fra Infotrygd er endret, f.eks. i vedtaksinformasjonen. Om den nye informasjonen i Infotrygd er korrekt og fører til at saken ikke støttes i Speil, må den annulleres.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_28'), 'Perioden er en direkte overgang fra periode i Infotrygd', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_29'), 'Perioden er lagt inn i Infotrygd - men mangler inntektsopplysninger. Fjern perioden fra SP UB hvis du utbetaler via speil.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_30'), 'Perioden er lagt inn i Infotrygd, men ikke utbetalt. Fjern fra Infotrygd hvis det utbetales via speil.', 'Det ligger registrert en søknad om sykepenger på SP UB.', 'Dette varselet betyr ikke at perioden må behandles i Infotrygd. Fjern perioden fra SP UB når du utbetaler via speil. Hvis inntekten er registert så kan den slettes på SP-VT. Hvis det er en forutgående periode i Infotrygd som enda ikke er behandlet, trenger du ikke å avvise perioden hvis det er flere sykepengedager igjen er enn det som ligger til behandling i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_31'), 'Perioden forlenger en behandling i Infotrygd, og har historikk fra ny løsning: Undersøk at antall dager igjen er beregnet riktig.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_32'), 'Perioden forlenger en behandling i ny løsning, og har historikk i Infotrygd også: Undersøk at antall dager igjen er beregnet riktig.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IT_33'), 'Skjæringstidspunktet har endret seg som følge av historikk fra Infotrygd', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_1'), 'Arbeidsgiver er ikke registrert i Aa-registeret.', 'Arbeidsgiver på sykmelding eller inntektsmelding er ikke registrert i Aa-registeret.', 'Sjekk at bruker er ansatt hos arbeidsgiveren.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_2'), 'Flere arbeidsgivere, ulikt starttidspunkt for sykefraværet eller ikke fravær fra alle arbeidsforhold', 'Det tidligste sykefraværet bestemmer skjæringstidspunktet. Dette gjelder: Inntekt på inntektsmeldingen som kommer fra arbeidsgivere med senere starttidspunkt kan gjelde feil periode og/eller inntekten som er foreslått for minst et av arbeidsforholdene er innhentet fra a-ordningen og er gjennomsnittet av rapportert inntekt de tre siste månedene før tidspunktet for arbeidsuførhet (§8-28 3. ledd bokstav a).', 'Du må fastsette et sykepengegrunnlag basert på inntekt fra alle arbeidsforholdene. Du må vurdere om de foreslåtte arbeidsforholdene er reelle og skal tas med i beregningen.  Hvis det er kommet inntektsmelding fra arbeidsgiver med senere starttidspunkt, må det sjekkes om inntekten for dette arbeidsforholdet er riktig beregnet (§8-28). Hvis det ikke er kommet inntektsmelding fra denne arbeidsgiveren, må den foreslåtte inntekten vurderes. Du må vurdere om den innhentede inntekten er riktig. Sjekk om det er et nytt arbeidsforhold eller varig lønnsendring i beregningsperioden. Sjekk om det variasjoner i inntekten som kan bety at det er lovlig fravær uten lønn i beregningsperioden. Vurderes etter §8-28.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_3'), 'Første utbetalingsdag er i Infotrygd og mellom 1. og 16. mai. Kontroller at riktig grunnbeløp er brukt.', 'Vi klarer ikke å lese riktig skjæringstidspunkt når saken har startet i Infotrygd. Vi må kontrollere at riktig grunnbeløp er brukt i saker med sykepengegrunnlag over 6G.', 'Kontroller at dagsatsen samsvarer med grunnbeløpet som skal brukes.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_4'), 'Minst én dag uten utbetaling på grunn av sykdomsgrad under 20 %. Vurder å sende vedtaksbrev fra Infotrygd', 'Minst én dag uten utbetaling på grunn av sykdomsgrad under 20', 'Dersom du er enig i vurderingen, send avslagsbrev fra Infotrygd og godkjenn i ny løsning. OBS!!: Hør med den som er sykmeldt hvis det er mistanke om misforståelser ved utfylling av søknaden. Da kan du sende spørsmål i Modia og legge saken på vent til du får svar.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_5'), 'Bruker mangler nødvendig inntekt ved validering av Vilkårsgrunnlag', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_8'), 'Den sykmeldte har skiftet arbeidsgiver, og det er beregnet at den nye arbeidsgiveren mottar refusjon lik forrige. Kontroller at dagsatsen blir riktig.', 'Den sykmeldte har skiftet arbeidsgiver i løpet av sykefraværet.', 'Sjekk at riktig dagsats er lagt til grunn.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_9'), 'Bruker er fortsatt syk 26 uker etter maksdato', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_10'), 'Fant ikke vilkårsgrunnlag. Kan ikke vilkårsprøve på nytt etter ny informasjon fra saksbehandler.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_11'), 'Vilkårsgrunnlaget ligger i infotrygd. Det er ikke støttet i revurdering eller overstyring.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_12'), 'Kan ikke overstyre inntekt uten at det foreligger et vilkårsgrunnlag', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_13'), '26 uker siden forrige utbetaling av sykepenger, vurder om vilkårene for sykepenger er oppfylt', 'Bruker har tidligere fått utbetalt sykepenger til maksdato. Det er nå mer enn 26 uker siden siste utbetaling av sykepenger(§ 8-12).', 'Saken må behandles som en førstegangssak og alle vilkårene for å få sykepenger må vurderes.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_14'), 'Denne personen har en utbetaling for samme periode for en annen arbeidsgiver. Kontroller at beregningene for begge arbeidsgiverne er korrekte.', 'Da vi beregnet den forrige utbetalingen visste vi ikke at personen var syk for denne arbeidsgiveren.', 'Det kan hende at begge beregningene er riktig, men dette må kontrolleres. Hvis det er feil må perioder som er ferdig behandlet annulleres og alt må behandles i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_15'), 'Maks antall sykepengedager er nådd i perioden', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VV_16'), 'Søknaden inneholder egenmeldingsdager som ikke er oppgitt i inntektsmeldingen. Vurder om arbeidsgiverperioden beregnes riktig', 'Egenmeldingsdager er ikke oppgitt i inntektsmeldingen, men i søknaden', 'Sjekk om arbeidsgiver har oppgitt riktig arbeidsgiverperioden.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_OV_1'), 'Perioden er avslått på grunn av manglende opptjening', 'Alle dager er avvist på grunn av at personen ikke har jobbet mer enn fire uker før sykmeldingstidspunktet', 'Undersøk at opptjeningen er vurdert riktig. Hvis opptjening ikke er oppfylt kan saken godkjennes i speil og det må sendes avslagsbrev i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_OV_2'), 'Opptjeningsvurdering må gjøres manuelt fordi opplysningene fra AA-registeret er ufullstendige', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_MV_1'), 'Vurder lovvalg og medlemskap', 'Medlemskapssjekken har ikke klart å entydig konkludere med at bruker er medlem', 'Sjekk om personen er medlem i folketrygden – se i medlemskapsfanen i Gosys. Sjekk bostedsadressen og hvor arbeidet utføres. Hvis bokommune er 0393 eller 2101 skal saken avvises og behandles av NAV Utland. Kilder: Gosys og Aa-registeret.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_MV_2'), 'Perioden er avslått på grunn av at den sykmeldte ikke er medlem av Folketrygden', 'Alle dager er avvist på grunn av at personen ikke er medlem av Folketrygden', 'Undersøk om det er riktig at personen ikke er medlem av Folketrygden. Hvis personen ikke er medlem kan saken godkjennes i speil og det må sendes vedtak i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IV_1'), 'Bruker har flere inntektskilder de siste tre månedene enn arbeidsforhold som er oppdaget i Aa-registeret.', 'Bruker kan være frilanser.', 'Sjekk om bruker er kombinert arbeidstaker og frilanser. Hvis ja, send saken til Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IV_2'), 'Har mer enn 25 % avvik. Dette støttes foreløpig ikke i Speil. Du må derfor annullere periodene.', 'Det er lagt inn en ny inntekt som gir 25 % avvik. Skjønnsmessig fastsettelse av sykepengegrunnlaget støttes ikke i Speil.', 'Du kan endre inntekten en gang til hvis du har gjort noe feil. Dersom endringen skal gjennomføres må periodene annulleres i Speil og behandles i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IV_3'), 'Fant frilanserinntekt på en arbeidsgiver de siste 3 månedene', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IV_4'), 'Finnes inntekter fra flere virksomheter siste tre måneder', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IV_5'), 'Har inntekt på flere arbeidsgivere med forskjellig fom dato', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_IV_6'), 'Inntekter fra mer enn én arbeidsgiver i A-ordningen siste tre måneder. Kontroller om brukeren har flere arbeidsforhold på sykmeldingstidspunktet. Flere arbeidsforhold støttes ikke av systemet.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SV_1'), 'Perioden er avslått på grunn av at inntekt er under krav til minste sykepengegrunnlag', 'Alle dager er avvist på grunn av at sykepengegrunnlaget er under minstekrav', 'Undersøk at sykepengegrunnlaget er korrekt. Hvis det er fastsatt korrekt kan saken godkjennes i speil, da må avslagsbrev sendes i infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SV_2'), 'Minst en arbeidsgiver inngår ikke i sykepengegrunnlaget', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SV_3'), 'Mangler inntekt for sykepengegrunnlag som følge av at skjæringstidspunktet har endret seg', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SV_4'), 'Brukeren har flere inntekter de siste tre måneder. Kontroller om brukeren har flere arbeidsforhold eller andre ytelser på sykmeldingstidspunktet som påvirker utbetalingen.', 'Det finnes inntekter fra mer enn én arbeidsgiver i A-ordningen i de siste tre månedene', 'Sjekk om den sykmeldte har flere aktive inntektskilder på sykmeldingstidspunktet. Speil håndterer ikke kombinasjonen arbeidstaker og frilanser. I slike tilfeller må saken behandles i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_3'), 'Bruker har mottatt AAP innenfor 6 måneder før skjæringstidspunktet. Kontroller at brukeren har rett til sykepenger', 'Bruker har mottatt AAP innenfor 6 måneder før skjæringstidspunktet', 'Kontrollér ny opptjeningstid etter maksdato'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_4'), 'Bruker har mottatt dagpenger innenfor 4 uker før skjæringstidspunktet. Kontroller om bruker er dagpengemottaker. Kombinerte ytelser støttes foreløpig ikke av systemet', 'Bruker har mottatt dagpenger innenfor 4 uker før skjæringstidspunktet', 'Sjekk om bruker er dagpengemottaker på sykmeldingstidspunktet. Hvis ja kan ikke saken behandles i dette systemet ennå.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_5'), 'Det er utbetalt foreldrepenger i samme periode.', 'Det er utbetalt foreldrepenger i Infotrygd etter at perioden ble godkjent i Speil.', 'Undersøk hvilken ytelse som er riktig. Hvis utbetalingene i Speil må avslås på grunn av andre ytelser må du annullere og behandle i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_6'), 'Det er utbetalt pleiepenger i samme periode.', 'Det er utbetalt pleiepenger i Infotrygd etter at perioden ble godkjent i Speil.', 'Undersøk hvilken ytelse som er riktig. Hvis utbetalingene i Speil må avslås på grunn av andre ytelser må du annullere og behandle i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_7'), 'Det er utbetalt omsorgspenger i samme periode.', 'Det er utbetalt omsorgspenger i Infotrygd etter at perioden ble godkjent i Speil.', 'Undersøk hvilken ytelse som er riktig. Hvis utbetalingene i Speil må avslås på grunn av andre ytelser må du annullere og behandle i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_8'), 'Det er utbetalt opplæringspenger i samme periode.', 'Det er utbetalt opplæringspenger i Infotrygd etter at perioden ble godkjent i Speil.', 'Undersøk hvilken ytelse som er riktig. Hvis utbetalingene i Speil må avslås på grunn av andre ytelser må du annullere og behandle i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_9'), 'Det er institusjonsopphold i perioden. Vurder retten til sykepenger.', 'Vi henter inn opplysninger om institusjonsopphold. Det har kommet informasjon om at den sykmeldte oppholdt seg i institusjon (sykehus eller fengsel) i perioden.', 'Undersøk om institusjonsoppholdet er forenlig med å motta sykepenger. Dersom en periode skal avslås på grunn av institusjonsopphold må saken annulleres og behandles i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AY_10'), 'Behandling av Ytelser feilet, årsak ukjent', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SI_1'), 'Feil under simulering', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SI_2'), 'Simulering av revurdert utbetaling feilet. Utbetalingen må annulleres', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SI_3'), 'Det er simulert et negativt beløp.', 'Vedtaksløsningen foreslår å omgjøre tidligere utbetaling av sykepenger, slik at hele eller deler av simuleringen gir et negativt beløp.', 'Undersøk om simuleringen gir et ønsket og riktig resultat og korriger hvis simuleringen er feil. Hvis simuleringen er riktig, se rutine for revurdering, feilutbetaling og tilbakekreving.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SI_4'), 'Ingenting ble simulert', 'Det er oppgitt ferieavvikling i hele søknadsperioden', 'Sjekk om ferieavvikling er oppgitt i søknaden'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SI_5'), 'Simulering har endret dagsats eller antall på én eller flere utbetalingslinjer', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SI_6'), 'Simulering inneholder ikke alle periodene som skal betales', 'Perioder som  anvises mangler i simuleringen', 'Send saken til manuell behandling i Infotrygd.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_SI_7'), 'Simulering kom frem til et annet totalbeløp. Kontroller beløpet til utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_1'), 'Utbetaling av revurdert periode ble avvist av saksbehandler. Utbetalingen må annulleres', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_2'), 'Utbetalingen ble gjennomført, men med advarsel', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_3'), 'Feil ved utbetalingstidslinjebygging', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_4'), 'Finner ingen utbetaling å annullere', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_5'), 'Utbetaling ble ikke gjennomført', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_6'), 'Forventet ikke å opprette utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_7'), 'Forventet ikke godkjenning på utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_8'), 'Forventet ikke å etterutbetale på utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_9'), 'Forventet ikke å annullere på utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_10'), 'Forventet ikke overførtkvittering på utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_11'), 'Forventet ikke kvittering på utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_12'), 'Forventet ikke simulering på utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_13'), 'Forventet ikke å lage godkjenning på utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_14'), 'Gir opp å prøve utbetaling på nytt', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_15'), 'Kan ikke annullere: hendelsen er ikke relevant', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_16'), 'Feil ved kalkulering av utbetalingstidslinjer', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_17'), 'Utbetaling feilet', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_18'), 'Utbetaling markert som ikke godkjent automatisk', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_19'), 'Utbetaling markert som ikke godkjent av saksbehandler', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_20'), 'Utbetaling fra og med dato er endret. Kontroller simuleringen', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_UT_21'), 'Utbetaling opphører tidligere utbetaling. Kontroller simuleringen', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_OS_1'), 'Utbetalingen forlenger et tidligere oppdrag som opphørte alle utbetalte dager. Sjekk simuleringen.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_OS_2'), 'Utbetalingens fra og med-dato er endret. Kontroller simuleringen', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_OS_3'), 'Endrer tidligere oppdrag. Kontroller simuleringen.', 'Det er opphørt en tidligere linje i Oppdrag. Dette skjer dersom en FOM-dato på en linje endrer seg.', 'Undersøk om perioden blir riktig simulert, og ta en sjekk på oppdraget i ettertid'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_RV_1'), 'Denne perioden var tidligere regnet som innenfor arbeidsgiverperioden', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_RV_2'), 'Forkaster avvist revurdering ettersom vedtaksperioden ikke har tidligere utbetalte utbetalinger.', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_RV_3'), 'Forespurt revurdering av inntekt hvor personen har flere arbeidsgivere (inkl. ghosts)', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_RV_4'), 'Revurdering er igangsatt og må fullføres', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_RV_5'), 'Validering av ytelser ved revurdering feilet. Utbetalingen må annulleres', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VT_1'), 'Gir opp fordi tilstanden er nådd makstid', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VT_2'), 'Forventet ikke vilkårsgrunnlag', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VT_3'), 'Forventet ikke utbetalingsgodkjenning', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VT_4'), 'Forventet ikke simulering', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VT_5'), 'Forventet ikke utbetaling', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VT_6'), 'Forventet ikke overstyring fra saksbehandler', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_VT_7'), 'Forventet ikke ytelsehistorikk', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'RV_AG_1'), 'Finner ikke arbeidsgiver', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_BO_1'), 'Beslutteroppgave: Lovvalg og medlemskap', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_BO_2'), 'Beslutteroppgave: Overstyring av utbetalingsdager', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_BO_3'), 'Beslutteroppgave: Overstyring av inntekt', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_BO_4'), 'Beslutteroppgave: Overstyring av annet arbeidsforhold', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_BO_5'), 'Beslutteroppgave: Lovvalg og medlemskap og/eller overstyring av utbetalingsdager og/eller overstyring av inntekt og/eller overstyring av annet arbeidsforhold', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_EX_1'), 'Det finnes åpne oppgaver på sykepenger i Gosys', 'Det ligger aktive oppgaver med tema sykepenger i Gosys.', 'Sjekk Gosys-oppgavene og vurder om de påvirker saksbehandlingen.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_EX_2'), 'Ikke registrert eller mangler samtykke i Kontakt- og reservasjonsregisteret, eventuell kommunikasjon må skje i brevform', 'Brukeren ikke har bekreftet valget om reservasjon de siste 18 månedene.', 'Dersom vi ønsker å kommunisere med brukeren, enten for å sende et vedtak eller hente inn informasjon, må det være på brev og ikke i automatiske løsninger.'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_EX_3'), 'Kunne ikke sjekke åpne oppgaver på sykepenger i Gosys', 'Den automatiske sjekken etter Gosys-oppgaver har feilet, og vi vet ikke om det finnes Gosys-oppgaver eller ikke', 'Undersøk om det er åpne Gosys-oppgaver på sykepenger på bruker, og vurder om saken kan behandles ut i fra innholdet i oppgaven(e)'),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_IK_1'), 'Registrert fullmakt på personen', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_RV_1'), 'Faresignaler oppdaget. Kontroller om faresignalene påvirker retten til sykepenger', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_RV_2'), 'Veileder har stanset automatisk behandling. Se Gosys for mer informasjon', null, null),
                                                                    ((SELECT id FROM varselkode WHERE kode = 'SB_RV_3'), 'Kunne ikke sjekke om veileder har stanset automatisk behandling på grunn av teknisk feil', null, null)
;