apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speaker-backend
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://speaker.intern.dev.nav.no
  strategy:
    type: Recreate
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
      allowAllUsers: false
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        name: speaker-db
        databases:
          - name: speaker
            envVarPrefix: DATABASE
            users:
              - name: speaker-kafka
  secureLogs:
    enabled: true
  env:
    - name: AZURE_VALID_GROUP_ID
      value: "f787f900-6697-440d-a086-d5bb56e26a9c"
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-speaker-backend-v1
    - name: MS_GRAPH_BASE_URL
      value: "https://graph.microsoft.com/v1.0"
