apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speaker-backend
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://speaker.dev.intern.nav.no
  strategy:
    type: Recreate
  liveness:
    path: internal/isalive
    initialDelay: 5
  readiness:
    path: internal/isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  azure:
    application:
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
      replyURLs:
        - "https://speaker.dev.intern.nav.no/oauth2/callback"
      allowAllUsers: false
  prometheus:
    enabled: true
    path: /internal/metrics
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        name: speaker-db
        databases:
          - name: speaker
            envVarPrefix: DATABASE
            users:
              - name: speaker-kafka
  secureLogs:
    enabled: true
