apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speaker
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 10
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  accessPolicy:
    outbound:
      external:
        - host: api.sanity.io
        - host: z9kr8ddn.api.sanity.io
        - host: apicdn.sanity.io
        - host: z9kr8ddn.apicdn.sanity.io
        - host: cdn.sanity.io
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  gcp:
    buckets:
      - name: speaker-bucket-dev
        lifecycleCondition:
          numNewerVersions: 1
          withState: ANY
  env:
    - name: SANITY_PROJECT_ID
      value: z9kr8ddn
    - name: SANITY_DATASET
      value: production
    - name: BUCKET_NAME
      value: speaker-bucket-dev
