apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speaker-endringer-formidler
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  accessPolicy:
    outbound:
      external:
        - host: api.sanity.io
        - host: z9kr8ddn.api.sanity.io
        - host: apicdn.sanity.io
        - host: z9kr8ddn.apicdn.sanity.io
        - host: cdn.sanity.io
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-speaker-endringer-formidler-v1
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: SANITY_PROJECT_ID
      value: z9kr8ddn
    - name: SANITY_DATASET
      value: production
