apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: speaker-kafka
  namespace: tbd
  labels:
    team: tbd
    db: speakerdb
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 6Gi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-speaker-backend-speaker-speaker-kafka-59ac85c8
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-speaker-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "speaker-db"
    - name: DATABASE_NAME
      value: "speaker"