name: Speaker-endringer-formidler

on:
  workflow_dispatch:
  push:
    paths:
      - 'deploy/endringer-formidler-dev.yml'
      - 'deploy/endringer-formidler-prod.yml'
      - 'speaker-endringer-formidler/**'
      - 'build.gradle.kts'
      - '.github/workflows/speaker-endringer-formidler.yml'
      - 'Dockerfile-endringer-formidler'
    branches:
      - main

jobs:
  set_version:
    name: set image name
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      image: ghcr.io/${{ github.repository }}/speaker-endringer-formidler:${{ env.TAG }}

  build:
    name: build docker image
    runs-on: ubuntu-latest
    needs: set_version
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew :speaker-endringer-formidler:build :speaker-endringer-formidler:test :speaker-endringer-formidler:build
      - name: build docker image
        run: docker build -f Dockerfile-endringer-formidler . --pull -t ${{ needs.set_version.outputs.image }}
      - name: push docker image
        run: |
          docker login ghcr.io --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ needs.set_version.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: [set_version, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/endringer-formidler-dev.yml
          IMAGE: ${{ needs.set_version.outputs.image }}

#  deployProd:
#    name: deploy to prod
#    needs: [set_version, build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: nais/deploy/actions/deploy@v2
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: deploy/endringer-formidler-prod.yml
#          IMAGE: ${{ needs.set_version.outputs.image }}
