name: Speaker-endringer-formidler

on:
  workflow_dispatch:
  push:
    paths:
      - 'deploy/endringer-formidler-dev.yml'
      - 'deploy/endringer-formidler-prod.yml'
      - 'speaker-endringer-formidler/**'
      - 'build.gradle.kts'
      - '.github/workflows/speaker-endringer-formidler.yml'
      - 'Dockerfile-endringer-formidler'
    branches:
      - main

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test og bygg
        run: ./gradlew :speaker-endringer-formidler:build :speaker-endringer-formidler:build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Lag Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          dockerfile: Dockerfile-endringer-formidler
          cache_from: type=gha
          cache_to: type=gha,mode=max
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/endringer-formidler-dev.yml
          IMAGE: ${{ needs.build.outputs.image }}

  deployProd:
    name: deploy to prod
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/endringer-formidler-prod.yml
          IMAGE: ${{ needs.build.outputs.image }}
